
package numbers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Prime", targetNamespace = "http://numbers/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Prime {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isPrime", targetNamespace = "http://numbers/", className = "numbers.IsPrime")
    @ResponseWrapper(localName = "isPrimeResponse", targetNamespace = "http://numbers/", className = "numbers.IsPrimeResponse")
    @Action(input = "http://numbers/Prime/isPrimeRequest", output = "http://numbers/Prime/isPrimeResponse")
    public boolean isPrime(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
