
package numbers;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrimeImplService", targetNamespace = "http://numbers/", wsdlLocation = "http://localhost:8080/Prime/prime?wsdl")
@HandlerChain(file = "handlers/handler-chain.xml")
public class PrimeImplService
    extends Service
{

    private final static URL PRIMEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRIMEIMPLSERVICE_EXCEPTION;
    private final static QName PRIMEIMPLSERVICE_QNAME = new QName("http://numbers/", "PrimeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Prime/prime?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRIMEIMPLSERVICE_WSDL_LOCATION = url;
        PRIMEIMPLSERVICE_EXCEPTION = e;
    }

    public PrimeImplService() {
        super(__getWsdlLocation(), PRIMEIMPLSERVICE_QNAME);
    }

    public PrimeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRIMEIMPLSERVICE_QNAME, features);
    }

    public PrimeImplService(URL wsdlLocation) {
        super(wsdlLocation, PRIMEIMPLSERVICE_QNAME);
    }

    public PrimeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRIMEIMPLSERVICE_QNAME, features);
    }

    public PrimeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrimeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Prime
     */
    @WebEndpoint(name = "PrimeImplPort")
    public Prime getPrimeImplPort() {
        return super.getPort(new QName("http://numbers/", "PrimeImplPort"), Prime.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Prime
     */
    @WebEndpoint(name = "PrimeImplPort")
    public Prime getPrimeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://numbers/", "PrimeImplPort"), Prime.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRIMEIMPLSERVICE_EXCEPTION!= null) {
            throw PRIMEIMPLSERVICE_EXCEPTION;
        }
        return PRIMEIMPLSERVICE_WSDL_LOCATION;
    }

}
